[package]
name = "clementine"
version = "0.0.1"
authors = ["DavidCai <davidcai1993@yahoo.com>"]
readme = "README.md"
repository = "https://github.com/DavidCai1993/clementine"
license = "MIT"

[dependencies]
serde_json = "0.9"
